backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "projetos" # Used in routes, e.g., /admin/collections/blog
    label: "Projeto" # Used in the UI
    folder: "content/projects/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categorias", name: "areas", widget: "list"}
      - {label: "Publicado Em", name: "date", widget: "date"}
      - {label: "Capa", name: "cover", widget: "image"}
      - label: "Imagens"
        name: "images"
        widget: "list"
        field: {label: Image, name: image, widget: image}

